"""Turn a PreCommitConfig into (a) a config file and (b) an offline preview.

Both are pure functions of the model tables, which is what keeps them from drifting:
the hook list the user reads on the review screen and the `repos:` list pre-commit
executes are built from the same `selected()`.

The YAML is emitted as text rather than dumped through PyYAML, because the section
comments are part of the deliverable — a generated config people are expected to
hand-edit afterwards needs to say what each block is for, and no dumper can produce
that. `data()` builds the same content as a plain structure, and `to_yaml` is checked
against it by parsing the emitted text back (`_matches`), so the hand-written emitter
cannot silently disagree with the model (SD-3).
"""

from __future__ import annotations

import re
from typing import Any

import yaml

from dev_setup.configure.precommit.model import (
    DOCS_URL,
    GROUPS,
    PRESETS,
    Hook,
    PreCommitConfig,
)

GENERATED_HEADER = "# pre-commit configuration"
GENERATED_BY = "# Generated by `devstuff configure pre-commit` — edit freely, or re-run the wizard."

# A scalar that *might* be safe to write bare: no leading indicator character, no
# comment marker, nothing needing an escape. Necessary but not sufficient — see below.
_PLAIN_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/:+=@-]*$")


def _str(value: str) -> str:
    """A YAML scalar, single-quoted unless writing it bare provably round-trips.

    The rule is measured rather than reasoned about: a candidate is written bare only
    if the regex above says it carries no syntax *and* `yaml.safe_load` reads it back
    as the identical string. That second half is what catches the coercions a
    hand-written table always misses — `2` (shfmt's indent width) and a rev like
    `1.0` both come back as numbers, and pre-commit's schema requires strings.

    Everything else is single-quoted, which is YAML's literal form: nothing inside is
    escaped except `'` itself, doubled. That is why the regex in `exclude` reaches
    pre-commit exactly as it was typed. (The same reasoning as the TOML literal
    strings in the commitizen configurator.)
    """
    if _PLAIN_RE.match(value):
        try:
            if yaml.safe_load(value) == value:
                return value
        except yaml.YAMLError:
            pass
    return "'" + value.replace("'", "''") + "'"


def _flow_list(values: list[str]) -> str:
    return "[" + ", ".join(_str(v) for v in values) + "]" if values else "[]"


# ---------------------------------------------------------------------------
# The config as data
# ---------------------------------------------------------------------------


def hook_entry(hook: Hook) -> dict[str, Any]:
    """One `hooks:` entry. Only keys that differ from the hook's own defaults are
    written — a config restating what the upstream repo already declares is a config
    that goes stale the next time upstream changes it."""
    entry: dict[str, Any] = {"id": hook.id}
    if hook.args:
        entry["args"] = list(hook.args)
    if hook.additional_dependencies:
        entry["additional_dependencies"] = list(hook.additional_dependencies)
    if hook.types_or:
        entry["types_or"] = list(hook.types_or)
    if hook.files:
        entry["files"] = hook.files
    if hook.exclude:
        entry["exclude"] = hook.exclude
    # `stages` is deliberately absent: the hook declares its own, and repeating them
    # here means a config that has to be re-edited when upstream moves a hook to a
    # different stage. What *is* derived from them is `default_install_hook_types`.
    return entry


def ci_skip(cfg: PreCommitConfig) -> list[str]:
    """Hooks pre-commit.ci cannot run.

    pre-commit.ci runs no Docker daemon, so every `language: docker` /
    `docker_image` hook fails there with a container error rather than a lint
    failure. Listing them under `ci.skip` is the documented way to keep the rest
    of the run green.
    """
    return [h.id for h in cfg.selected() if h.needs == "docker"]


def data(cfg: PreCommitConfig) -> dict[str, Any]:
    """The whole config as a plain structure — what the emitted YAML must parse to."""
    out: dict[str, Any] = {}
    hook_types = cfg.install_hook_types()
    if hook_types != ["pre-commit"]:
        out["default_install_hook_types"] = hook_types
    if cfg.fail_fast:
        out["fail_fast"] = True
    if cfg.exclude:
        out["exclude"] = cfg.exclude
    if cfg.use_ci:
        ci: dict[str, Any] = {"autoupdate_schedule": cfg.autoupdate_schedule}
        skip = ci_skip(cfg)
        if skip:
            ci["skip"] = skip
        out["ci"] = ci
    out["repos"] = [
        {
            "repo": repo.url,
            "rev": repo.rev,
            "hooks": [hook_entry(hook) for hook in hooks],
        }
        for repo, hooks in cfg.by_repo()
    ]
    return out


# ---------------------------------------------------------------------------
# YAML emission
# ---------------------------------------------------------------------------


def _hook_lines(hook: Hook, indent: str) -> list[str]:
    entry = hook_entry(hook)
    out = [f"{indent}- id: {_str(entry['id'])}"]
    inner = indent + "  "
    for key in ("args", "additional_dependencies", "types_or"):
        if key in entry:
            out.append(f"{inner}{key}: {_flow_list(entry[key])}")
    for key in ("files", "exclude"):
        if key in entry:
            out.append(f"{inner}{key}: {_str(entry[key])}")
    return out


def _repo_lines(cfg: PreCommitConfig) -> list[str]:
    grouped = cfg.by_repo()
    if not grouped:
        # `repos:` with nothing under it parses as null, not as an empty list, and
        # pre-commit rejects it. A config with no hooks is pointless but it must still
        # be a config that loads.
        return ["repos: []"]
    out = ["repos:"]
    for repo, hooks in grouped:
        out += [
            f"  - repo: {repo.url}",
            f"    rev: {_str(repo.rev)}",
            "    hooks:",
        ]
        seen_groups: set[str] = set()
        for hook in hooks:
            # One comment per group within a repo. pre-commit-hooks holds hooks from
            # five different groups, and an unannotated run of twenty ids is the part
            # of a generated config nobody can read six months later.
            if hook.group not in seen_groups and len(set(h.group for h in hooks)) > 1:
                seen_groups.add(hook.group)
                out.append(f"      # {GROUPS[hook.group].label}")
            out += _hook_lines(hook, "      ")
    return out


def _header(cfg: PreCommitConfig) -> list[str]:
    preset = PRESETS.get(cfg.preset)
    label = preset.label if preset else cfg.preset
    count = len(cfg.selected())
    return [
        GENERATED_HEADER,
        GENERATED_BY,
        f"# Preset: {label} · {count} hook{'s' if count != 1 else ''}",
        f"# Option reference: {DOCS_URL}",
        "#",
        "# Install the git hooks:   pre-commit install"
        + (
            f" --install-hook-types {','.join(cfg.install_hook_types())}"
            if cfg.install_hook_types() != ["pre-commit"]
            else ""
        ),
        "# Run against everything:  pre-commit run --all-files",
        "# Bump every rev:          pre-commit autoupdate",
        "",
    ]


def to_yaml(cfg: PreCommitConfig) -> str:
    """The complete `.pre-commit-config.yaml`."""
    lines = _header(cfg)
    hook_types = cfg.install_hook_types()
    if hook_types != ["pre-commit"]:
        lines += [
            "# `pre-commit install` only installs the pre-commit hook unless it is told",
            "# otherwise, so the hooks below that run at another stage need this to run at all.",
            f"default_install_hook_types: {_flow_list(hook_types)}",
            "",
        ]
    if cfg.fail_fast:
        lines += ["# Stop at the first failing hook instead of running them all.",
                  "fail_fast: true", ""]
    if cfg.exclude:
        lines += ["# Paths no hook ever looks at.",
                  f"exclude: {_str(cfg.exclude)}", ""]
    if cfg.use_ci:
        lines += ["# Settings read by pre-commit.ci, ignored when running locally.", "ci:",
                  f"  autoupdate_schedule: {_str(cfg.autoupdate_schedule)}"]
        skip = ci_skip(cfg)
        if skip:
            lines += [
                "  # pre-commit.ci has no Docker daemon, so these can only run locally.",
                f"  skip: {_flow_list(skip)}",
            ]
        lines.append("")
    lines += _repo_lines(cfg)
    return "\n".join(lines) + "\n"


def matches(text: str, cfg: PreCommitConfig) -> bool:
    """Whether the emitted text parses back to exactly the structure `data()` meant.

    The emitter writes YAML by hand for the sake of the comments; this is what stops
    a quoting bug in it from producing a file that is valid YAML but says something
    other than the model does.
    """
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError:
        return False
    return parsed == data(cfg)


# ---------------------------------------------------------------------------
# Offline preview
# ---------------------------------------------------------------------------


def hook_rows(cfg: PreCommitConfig) -> list[tuple[str, str, str, str]]:
    """(hook, repo, when it runs, what it does) for the review screen."""
    rows = []
    for hook in cfg.selected():
        from dev_setup.configure.precommit.model import REPOS

        stages = ", ".join(hook.effective_stages())
        what = "fixes" if hook.fixes else "checks"
        rows.append((hook.key, REPOS[hook.repo].label, stages, f"{what} — {hook.description}"))
    return rows


def stage_rows(cfg: PreCommitConfig) -> list[tuple[str, list[str]]]:
    """(stage, hooks running at it) — the answer to "when does this actually fire?"."""
    grouped: dict[str, list[str]] = {}
    for hook in cfg.selected():
        for stage in hook.effective_stages():
            grouped.setdefault(stage, []).append(hook.key)
    return list(grouped.items())


def summary(cfg: PreCommitConfig) -> list[tuple[str, str]]:
    """(label, value) pairs for the review screen."""
    hooks = cfg.selected()
    fixers = cfg.fixers()
    preset = PRESETS.get(cfg.preset)
    repos = [repo.label for repo, _ in cfg.by_repo()]
    return [
        ("Starting point", preset.label if preset else cfg.preset),
        ("Hooks", f"{len(hooks)} across {len(repos)} repositories"),
        ("Repositories", ", ".join(repos) or "none"),
        ("Rewrites files", f"{len(fixers)} — {', '.join(h.key for h in fixers)}" if fixers else "none"),
        ("Git hooks installed", ", ".join(cfg.install_hook_types())),
        ("Stop at first failure", "yes" if cfg.fail_fast else "no — run every hook"),
        ("Excluded paths", cfg.exclude or "none"),
        ("pre-commit.ci block", f"yes — autoupdate {cfg.autoupdate_schedule}" if cfg.use_ci else "no"),
        ("Writes to", cfg.target),
    ]


__all__ = [
    "GENERATED_BY",
    "GENERATED_HEADER",
    "ci_skip",
    "data",
    "hook_entry",
    "hook_rows",
    "matches",
    "stage_rows",
    "summary",
    "to_yaml",
]
