"""Turn a `BatConfig` into bat's config file.

bat's config file is a list of the same long options the command line takes, one per
line, with `#` comments — so it can carry a generated-by marker, unlike Docker's JSON.

The one thing to get right is quoting. Measured: an unquoted value containing a space
is split into separate arguments, so `--theme=Solarized (dark)` makes bat try to
*open a file called `(dark)`*. Many of the shipped theme names contain spaces, so
every string value is quoted — bat accepts quotes on values that do not need them.

`matches()` parses the emitted text back into the flags it sets and compares against
`flags()`, the same round-trip discipline as the other configurators.
"""

from __future__ import annotations

import shlex

from dev_setup.configure.bat.model import (
    AUTO_THEME,
    DEFAULT_COMPONENTS,
    SETTINGS,
    BatConfig,
)

GENERATED_HEADER = "# Generated by devstuff — devstuff configure bat"


def _quote(value: str) -> str:
    """Always quote. Measured: an unquoted `Solarized (dark)` is read as two
    arguments and bat tries to open `(dark)` as a file."""
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def flags(cfg: BatConfig) -> list[tuple[str, str]]:
    """(flag, value) for everything this config sets, in table order.

    A setting equal to bat's own default is omitted — the same reasoning as the
    Docker emitter: a config restating a default freezes it.
    """
    out: list[tuple[str, str]] = []

    if cfg.uses_auto_theme():
        # `auto` is bat's default, so it is only worth writing when it is being
        # steered by a light/dark pair.
        if cfg.theme_dark:
            out.append(("--theme-dark", cfg.theme_dark))
        if cfg.theme_light:
            out.append(("--theme-light", cfg.theme_light))
    elif cfg.theme:
        out.append(("--theme", cfg.theme))

    if not cfg.default_components():
        out.append(("--style", cfg.style()))

    for key in ("paging", "wrap", "italic_text"):
        value = getattr(cfg, key)
        if value != SETTINGS[key].default:
            out.append((SETTINGS[key].flag, str(value)))

    if cfg.pager:
        out.append(("--pager", cfg.pager))
    if cfg.tabs != SETTINGS["tabs"].default:
        out.append(("--tabs", str(cfg.tabs)))
    return out


def to_text(cfg: BatConfig) -> str:
    """The config file as it will be written."""
    lines = [
        GENERATED_HEADER,
        "# One command-line option per line. Anything here is overridden by a flag",
        "# you pass on the command line, and by the BAT_* environment variables.",
        "",
    ]

    if cfg.uses_auto_theme() and (cfg.theme_dark or cfg.theme_light):
        lines.append("# theme=auto is bat's default: it picks by the terminal's colours.")
        lines.append("# These say which theme it picks in each case.")

    for flag, value in flags(cfg):
        if flag == "--style":
            lines.append("")
            lines.append("# Decorations. 'plain' means none.")
        lines.append(f"{flag}={_quote(value)}")

    if cfg.extra:
        lines.append("")
        lines.append("# Kept from the previous config — not set by this wizard.")
        lines.extend(cfg.extra)

    return "\n".join(lines).rstrip("\n") + "\n"


def parse(text: str) -> tuple[list[tuple[str, str]], list[str]]:
    """Read a config file back into (flags, unrecognised lines).

    bat's own parser splits each line with shell rules, so this uses `shlex` rather
    than a hand-rolled splitter — the goal is to read what bat reads.
    """
    known = {setting.flag for setting in SETTINGS.values()}
    found: list[tuple[str, str]] = []
    extra: list[str] = []

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            tokens = shlex.split(line)
        except ValueError:
            extra.append(raw)
            continue
        if not tokens:
            continue
        flag, _, inline = tokens[0].partition("=")
        value = inline if inline or "=" in tokens[0] else (tokens[1] if len(tokens) > 1 else "")
        if flag in known:
            found.append((flag, value))
        else:
            extra.append(raw)
    return found, extra


def matches(text: str, cfg: BatConfig) -> bool:
    """Whether the emitted text parses back to the flags the model meant."""
    parsed, _ = parse(text)
    return parsed == flags(cfg)


# ---------------------------------------------------------------------------
# Review screen
# ---------------------------------------------------------------------------


def summary(cfg: BatConfig) -> list[tuple[str, str]]:
    if cfg.uses_auto_theme():
        theme = "auto"
        if cfg.theme_dark or cfg.theme_light:
            theme += f" — {cfg.theme_dark or 'default'} / {cfg.theme_light or 'default'}"
    else:
        theme = cfg.theme
    return [
        ("starting point", cfg.preset),
        ("theme", theme),
        ("decorations", ", ".join(cfg.components) if cfg.components else "none (plain)"),
        ("paging", cfg.paging + (f" via {cfg.pager}" if cfg.pager else "")),
        ("writes to", str(cfg.target)),
    ]


def flag_rows(cfg: BatConfig) -> list[tuple[str, str, str]]:
    """(flag, value, what it does) for the review table."""
    by_flag = {setting.flag: setting for setting in SETTINGS.values()}
    rows = []
    for flag, value in flags(cfg):
        setting = by_flag.get(flag)
        rows.append((flag, value, setting.description if setting else ""))
    if not rows:
        rows.append(("(nothing)", "", "every bat default applies"))
    return rows


def shell_block(cfg: BatConfig) -> str:
    """The ~/.bashrc block. Never contains a blank line.

    `base.remove_bashrc_block` ends its block at the first blank line, so a blank
    line here would orphan everything after it when the block is removed.
    """
    from dev_setup.configure.bat.model import SHELL_BITS

    return "\n".join(SHELL_BITS[key].line for key in cfg.shell_bits if key in SHELL_BITS)


def diff(old: str, new: str) -> list[str]:
    import difflib

    return list(
        difflib.unified_diff(
            old.splitlines(), new.splitlines(), fromfile="current", tofile="new", lineterm=""
        )
    )


__all__ = [
    "AUTO_THEME",
    "DEFAULT_COMPONENTS",
    "GENERATED_HEADER",
    "diff",
    "flag_rows",
    "flags",
    "matches",
    "parse",
    "shell_block",
    "summary",
    "to_text",
]
