"""Turn a `LazygitConfig` into `config.yml`, and read one back.

The emitter writes YAML by hand so the file can carry comments explaining what each
setting is for — the same arrangement, and the same round-trip guarantee, as the
pre-commit emitter: `data()` describes the structure, `to_yaml()` writes the text,
and `matches()` parses it back and compares.

**Loading needs a custom loader.** lazygit's own default config contains
`expandAll: =` — the keybinding for the equals key — and PyYAML's `SafeLoader` maps a
bare `=` to `tag:yaml.org,2002:value` and refuses the document. Anything here that
reads a lazygit config goes through `load()`, which resolves that tag back to the
string it plainly is. The emitter has the mirror-image duty: a value of `=` must be
quoted on the way out.
"""

from __future__ import annotations

import yaml

from dev_setup.configure.lazygit.model import (
    SETTINGS,
    YAML_VALUE_TAG,
    LazygitConfig,
)

GENERATED_HEADER = "# Generated by devstuff — devstuff configure lazygit"


class _Loader(yaml.SafeLoader):
    """SafeLoader that reads a bare `=` as the string it is, not YAML's value type."""


_Loader.add_constructor(YAML_VALUE_TAG, lambda loader, node: loader.construct_scalar(node))


def load(text: str) -> tuple[dict, bool]:
    """Parse a lazygit config. (parsed, ok)."""
    try:
        parsed = yaml.load(text, Loader=_Loader)  # noqa: S506 — _Loader derives from SafeLoader
    except yaml.YAMLError:
        return {}, False
    if parsed is None:
        return {}, True
    return (parsed, True) if isinstance(parsed, dict) else ({}, False)


def _set(tree: dict, path: str, value: object) -> None:
    node = tree
    parts = path.split(".")
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = value


def get(tree: dict, path: str, default: object = None) -> object:
    node: object = tree
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return default
        node = node[part]
    return node


def _merge(base: dict, extra: dict) -> dict:
    """Deep-merge carried-over subtrees under what the wizard sets.

    The wizard's value wins on a collision: the user just chose it. Anything the
    wizard does not model survives untouched.
    """
    out = dict(base)
    for key, value in extra.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _merge(out[key], value)
        elif key not in out:
            out[key] = value
    return out


def data(cfg: LazygitConfig) -> dict:
    """The config as a nested structure. Settings equal to lazygit's default are
    omitted — a file restating them freezes them across upgrades."""
    tree: dict = {}
    for key, setting in cfg.changed().items():
        _set(tree, setting.path, getattr(cfg, key))
    return _merge(tree, cfg.extra)


def _scalar(value: object) -> str:
    """A YAML scalar. Booleans and numbers bare; strings quoted unless plainly safe.

    Quoting is decided by asking the parser, the same rule as the pre-commit emitter:
    a string is written bare only if it reads back as itself. That is what keeps `=`,
    `no`, `2` and `0.3333` from changing meaning.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if text and not text.startswith((" ", "#")) and not text.endswith(" "):
        try:
            if yaml.safe_load(text) == text:
                return text
        except yaml.YAMLError:
            pass
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _emit(node: dict, indent: int, comments: dict[str, str], prefix: str) -> list[str]:
    lines: list[str] = []
    pad = "  " * indent
    for key, value in node.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            if not value:
                lines.append(f"{pad}{key}: {{}}")
                continue
            lines.append(f"{pad}{key}:")
            lines += _emit(value, indent + 1, comments, path)
            continue
        if isinstance(value, list):
            if not value:
                lines.append(f"{pad}{key}: []")
                continue
            if all(isinstance(item, (str, int, float, bool)) for item in value):
                lines.append(f"{pad}{key}:")
                lines += [f"{pad}  - {_scalar(item)}" for item in value]
                continue
            # A list of mappings — `customCommands` is the one that matters, and it is
            # among the things a lazygit user has most invested in. Hand-emitting it
            # would mean reimplementing a YAML dumper; there are no comments to
            # preserve inside a carried-over structure, so use the real one.
            lines.append(f"{pad}{key}:")
            lines += _dump_block(value, indent + 1)
            continue
        note = comments.get(path)
        if note:
            for chunk in _wrap(note, 76 - len(pad)):
                lines.append(f"{pad}# {chunk}")
        lines.append(f"{pad}{key}: {_scalar(value)}")
    return lines


def _dump_block(value: object, indent: int) -> list[str]:
    """A nested structure rendered by PyYAML and re-indented into the hand-written file."""
    text = yaml.safe_dump(value, default_flow_style=False, sort_keys=False, allow_unicode=True)
    pad = "  " * indent
    return [f"{pad}{line}" if line.strip() else line for line in text.rstrip("\n").splitlines()]


def _wrap(text: str, width: int) -> list[str]:
    import textwrap

    return textwrap.wrap(text, width=max(width, 30)) or [text]


def to_yaml(cfg: LazygitConfig) -> str:
    """The file as it will be written."""
    comments = {
        setting.path: setting.why for setting in SETTINGS.values() if setting.why
    }
    lines = [
        GENERATED_HEADER,
        "#",
        "# lazygit ignores keys it does not recognise, so a setting copied from an",
        "# out-of-date guide starts cleanly and does nothing. Every key below was",
        "# verified against this lazygit before being written.",
        "#",
        "# See every available option:  lazygit --config",
        "",
    ]
    tree = data(cfg)
    if not tree:
        lines.append("# Nothing is set — every lazygit default applies.")
        return "\n".join(lines) + "\n"
    lines += _emit(tree, 0, comments, "")
    return "\n".join(lines) + "\n"


def matches(text: str, cfg: LazygitConfig) -> bool:
    """Whether the emitted text parses back to what the model meant."""
    parsed, ok = load(text)
    return ok and parsed == data(cfg)


# ---------------------------------------------------------------------------
# Review screen
# ---------------------------------------------------------------------------


def summary(cfg: LazygitConfig) -> list[tuple[str, str]]:
    rows = [
        ("starting point", cfg.preset),
        ("settings", str(len(cfg.changed()))),
        ("icons", cfg.nerd_fonts_version and f"Nerd Font v{cfg.nerd_fonts_version}" or "off"),
        ("diff pager", cfg.pager or "git's own"),
        ("writes to", str(cfg.target)),
    ]
    if cfg.extra:
        rows.append(("carried over", ", ".join(sorted(cfg.extra))))
    return rows


def setting_rows(cfg: LazygitConfig) -> list[tuple[str, str, str, str]]:
    """(group, path, value, note)."""
    from dev_setup.configure.lazygit.model import GROUPS

    rows = []
    for key, setting in cfg.changed().items():
        value = getattr(cfg, key)
        rows.append((
            GROUPS[setting.group].label,
            setting.path,
            _scalar(value),
            setting.why or setting.description,
        ))
    for key in cfg.extra:
        rows.append(("Carried over", key, "…", "not set by this wizard"))
    return rows


def diff(old: str, new: str) -> list[str]:
    import difflib

    return list(
        difflib.unified_diff(
            old.splitlines(), new.splitlines(), fromfile="current", tofile="new", lineterm=""
        )
    )


__all__ = [
    "GENERATED_HEADER",
    "data",
    "diff",
    "get",
    "load",
    "matches",
    "setting_rows",
    "summary",
    "to_yaml",
]
