"""Turn a CommitizenConfig into (a) a config file and (b) an offline preview.

Both outputs are pure functions of the model tables, which is what keeps them from
drifting apart: the bump table the user reads and the `bump_map` commitizen executes
are built from the same `selected()` list. The TOML is emitted as text rather than
serialised, because the header comments are part of the deliverable and no TOML
writer in the stdlib can produce them at all (SD-3).
"""

from __future__ import annotations

import tomllib
from typing import Any

from dev_setup.configure.commitizen.model import (
    ALWAYS_ACCEPTED,
    BREAKING_KEYWORD,
    BREAKING_SECTION,
    DEFAULT_BUMP_MESSAGE,
    MAJOR,
    MINOR,
    NONE,
    SAMPLE_BUMPS,
    SAMPLE_VERSION,
    ChangeType,
    CommitizenConfig,
)

DOCS_URL = "https://commitizen-tools.github.io/commitizen/config/"
GENERATED_HEADER = "# Commitizen configuration"
PYPROJECT_MARKER = "# Commitizen — generated by `devstuff configure commitizen`"

# `!` in the commit title is checked before anything else, so a breaking change is
# breaking whatever its type. Anchored on the whole matched prefix (`feat(api)!`),
# which is what commitizen matches `bump_map` keys against.
BREAKING_BANG = r"^.+!$"
# The footer form. `[\-\ ]` is commitizen's own spelling: both `BREAKING CHANGE`
# and `BREAKING-CHANGE` are legal in the Conventional Commits grammar.
BREAKING_FOOTER = r"^BREAKING[\-\ ]CHANGE"


# ---------------------------------------------------------------------------
# TOML scalars
# ---------------------------------------------------------------------------


def _basic(value: str) -> str:
    """A TOML *basic* string, for anything that has to carry a real newline."""
    out = value.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{out}"'


def _str(value: str) -> str:
    """A TOML string, literal when it can be.

    Literal strings process no escapes, which is the whole reason the generated
    regexes stay readable — `\\(.+\\)` reaches commitizen as written instead of
    needing every backslash doubled. A value carrying a quote or a newline cannot
    be a single-line literal, so it falls back to an escaped basic string.
    """
    if "'" in value or "\n" in value or "\r" in value:
        return _basic(value)
    return f"'{value}'"


def _val(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return str(value)
    if isinstance(value, list | tuple):
        return "[" + ", ".join(_val(item) for item in value) + "]"
    return _str(str(value))


def _kv(key: str, value: Any) -> str:
    return f"{key} = {_val(value)}"


# ---------------------------------------------------------------------------
# The generated regexes and maps
# ---------------------------------------------------------------------------


def _alternation(keys: list[str]) -> str:
    return "|".join(keys)


def bump_pattern(cfg: CommitizenConfig) -> str:
    """The regex whose **group 1** commitizen matches `bump_map` keys against.

    Every selected type is listed, including the ones that never bump: a type that
    matches here but has no `bump_map` entry is simply "no increment", whereas a type
    missing from the pattern would fall through to the same answer by accident.
    """
    keys = [BREAKING_KEYWORD.replace(" ", r"[\-\ ]")] + [t.key for t in cfg.selected()]
    return r"^((" + _alternation(keys) + r")(\(.+\))?!?):"


def bump_map(cfg: CommitizenConfig, *, major_version_zero: bool = False) -> dict[str, str]:
    """Ordered prefix → increment.

    Order is load-bearing: commitizen walks the keys and stops at the first `re.match`,
    so the two breaking-change rules have to come before the per-type ones or a
    `feat(api)!` would be read as a plain MINOR.
    """
    breaking = MINOR if major_version_zero else MAJOR
    out: dict[str, str] = {BREAKING_BANG: breaking, BREAKING_FOOTER: breaking}
    for change_type in cfg.selected():
        if change_type.bump != NONE:
            out[f"^{change_type.key}"] = change_type.bump
    return out


def change_type_map(cfg: CommitizenConfig) -> dict[str, str]:
    return {t.key: t.section for t in cfg.changelog_types()}


def change_type_order(cfg: CommitizenConfig) -> list[str]:
    """Changelog section order. Breaking changes lead — commitizen files them under
    their own heading rather than the originating type's."""
    order = [BREAKING_SECTION]
    for change_type in cfg.changelog_types():
        if change_type.section not in order:
            order.append(change_type.section)
    return order


def commit_parser(cfg: CommitizenConfig) -> str:
    """Pulls change_type/scope/breaking/message out of a commit for the changelog.

    The trailing `|\\w+!` alternative is not decoration: it is what keeps a breaking
    change written against a type that has no changelog section (`docs!: …`) from
    dropping out of the release notes entirely. Verified against the binary — such a
    commit lands in an unlabelled group at the end of the release rather than
    vanishing, which is also what `cz_conventional_commits` does.
    """
    keys = [BREAKING_KEYWORD] + [t.key for t in cfg.changelog_types()]
    return (
        r"^((?P<change_type>"
        + _alternation(keys)
        + r")(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!)"
        r":\s(?P<message>.*)?"
    )


def changelog_pattern(cfg: CommitizenConfig) -> str:
    """Which commits are even considered for the changelog.

    Deliberately the same as `bump_pattern` (as `cz_conventional_commits` does):
    the narrowing happens in `commit_parser`, which drops anything without a mapped
    change type. Filtering twice would mean two regexes to keep in step.
    """
    return bump_pattern(cfg)


def schema(cfg: CommitizenConfig) -> str:
    body = "<type>(<scope>): <subject>"
    if cfg.ask_body:
        body += "\n<BLANK LINE>\n<body>"
    if cfg.ask_footer:
        body += "\n<BLANK LINE>\n(BREAKING CHANGE: )<footer>"
    return body


def schema_pattern(cfg: CommitizenConfig) -> str:
    keys = [t.key for t in cfg.selected()]
    keys += [key for key in ALWAYS_ACCEPTED if key not in keys]
    return (
        r"(?s)"  # so `.` matches the newline between title and body
        r"(" + _alternation(keys) + r")"
        r"(\(\S+\))?"
        r"!?"
        r": "
        r"([^\n\r]+)"
        r"((\n\n.*)|(\s*))?$"
    )


def message_template(cfg: CommitizenConfig) -> str:
    """The Jinja2 template commitizen renders the answers through.

    The breaking-change footer is only written when there is something to say in it —
    an empty `BREAKING CHANGE:` line reads as a mistake, and the `!` in the title is
    already what `bump_map` keys off.
    """
    parts = ["{{change_type}}"]
    if cfg.ask_scope:
        parts.append("{% if scope %}({{scope}}){% endif %}")
    parts.append("{% if breaking %}!{% endif %}: {{subject}}")
    if cfg.ask_body:
        parts.append("{% if body %}\n\n{{body}}{% endif %}")
    if cfg.ask_footer:
        parts.append(
            "{% if breaking and footer %}\n\n" + BREAKING_KEYWORD + ": {{footer}}"
            "{% elif footer %}\n\n{{footer}}{% endif %}"
        )
    return "".join(parts)


def example(cfg: CommitizenConfig) -> str:
    """A commit message that the generated `schema_pattern` accepts — asserted in
    the tests, and re-checked against the real binary by `validate.py`."""
    selected = cfg.selected()
    key = selected[0].key if selected else "feat"
    head = f"{key}(api): add rate limiting to the search endpoint"
    if not cfg.ask_body:
        return head
    return head + "\n\nrequests over 100/min now get a 429 instead of timing out"


def info(cfg: CommitizenConfig) -> str:
    """What `cz info` prints — the types table, so the rules are readable from the
    terminal instead of only from this file."""
    lines = ["Commit types in this project:", ""]
    width = max((len(t.key) for t in cfg.selected()), default=4) + 2
    for change_type in cfg.selected():
        bump = change_type.bump or "no release"
        lines.append(f"  {change_type.key:<{width}} {change_type.description} ({bump})")
    lines += [
        "",
        "Add ! after the type (feat!: ...) or a 'BREAKING CHANGE:' footer for a "
        "breaking change.",
    ]
    return "\n".join(lines)


def questions(cfg: CommitizenConfig) -> list[dict[str, Any]]:
    choices = [
        {
            "value": change_type.key,
            "name": f"{change_type.key}: {change_type.description}",
            **({"key": change_type.shortcut} if change_type.shortcut else {}),
        }
        for change_type in cfg.selected()
    ]
    out: list[dict[str, Any]] = [
        {
            "type": "list",
            "name": "change_type",
            "message": "Select the type of change you are committing",
            "choices": choices,
        }
    ]
    if cfg.ask_scope:
        out.append({
            "type": "input",
            "name": "scope",
            "message": "Scope — the part of the codebase (press enter to skip):",
        })
    out.append({
        "type": "input",
        "name": "subject",
        "message": "Short, imperative summary (lower case, no full stop):",
    })
    if cfg.ask_body:
        out.append({
            "type": "input",
            "name": "body",
            "message": "Longer description (press enter to skip):",
            "multiline": True,
        })
    out.append({
        "type": "confirm",
        "name": "breaking",
        "message": "Is this a breaking change?",
        "default": False,
    })
    if cfg.ask_footer:
        out.append({
            "type": "input",
            "name": "footer",
            "message": "Footer — breaking-change details, issue references (press enter to skip):",
        })
    return out


# ---------------------------------------------------------------------------
# TOML emission
# ---------------------------------------------------------------------------


def _settings_lines(cfg: CommitizenConfig) -> list[str]:
    provider = cfg.provider_spec
    out = [
        "[tool.commitizen]",
        _kv("name", cfg.convention_spec.name),
        _kv("version_provider", cfg.version_provider),
    ]
    if provider.needs_version:
        # The only provider with nowhere else to read the version from, so it is the
        # only one where writing `version` here is right rather than a stale copy.
        out.append(_kv("version", cfg.version))
    out += [
        _kv("version_scheme", cfg.version_scheme),
        _kv("tag_format", cfg.tag_format),
    ]
    if cfg.version_files:
        out.append(_kv("version_files", cfg.version_files))
    out += [
        _kv("update_changelog_on_bump", cfg.update_changelog_on_bump),
        _kv("changelog_file", cfg.changelog_file),
        _kv("changelog_incremental", cfg.changelog_incremental),
        _kv("changelog_merge_prerelease", cfg.changelog_merge_prerelease),
        _kv("major_version_zero", cfg.major_version_zero),
        _kv("annotated_tag", cfg.annotated_tag),
        _kv("gpg_sign", cfg.gpg_sign),
        _kv("allow_abort", cfg.allow_abort),
        _kv("use_shortcuts", cfg.use_shortcuts),
    ]
    if cfg.bump_message and cfg.bump_message != DEFAULT_BUMP_MESSAGE:
        out.append(_kv("bump_message", cfg.bump_message))
    return out


def _table(header: str, data: dict[str, Any]) -> list[str]:
    return [header] + [f"{_str(key)} = {_val(value)}" for key, value in data.items()]


def _question_lines(question: dict[str, Any]) -> list[str]:
    out = ["[[tool.commitizen.customize.questions]]"]
    for key, value in question.items():
        if key == "choices":
            out.append("choices = [")
            for choice in value:
                inline = ", ".join(f"{k} = {_val(v)}" for k, v in choice.items())
                out.append(f"  {{ {inline} }},")
            out.append("]")
        else:
            out.append(_kv(key, value))
    return out


def _customize_lines(cfg: CommitizenConfig) -> list[str]:
    out = [
        "# Commit message shape: the questions `cz commit` asks and the message it",
        "# builds out of the answers.",
        "[tool.commitizen.customize]",
        _kv("message_template", message_template(cfg)),
        _kv("example", example(cfg)),
        _kv("schema", schema(cfg)),
        _kv("schema_pattern", schema_pattern(cfg)),
        _kv("info", info(cfg)),
        "",
        "# Which commits `cz bump` reads, and how it parses them for the changelog.",
        _kv("bump_pattern", bump_pattern(cfg)),
        _kv("changelog_pattern", changelog_pattern(cfg)),
        _kv("commit_parser", commit_parser(cfg)),
        _kv("change_type_order", change_type_order(cfg)),
        "",
        "# Prefix -> version increment. Order matters: commitizen stops at the first",
        "# key that matches, so the two breaking-change rules have to lead.",
    ]
    out += _table("[tool.commitizen.customize.bump_map]", bump_map(cfg))
    out += [
        "",
        "# The same map for `major_version_zero`, where a breaking change is only",
        "# allowed to move the minor: 0.x is not promising anything yet.",
    ]
    out += _table(
        "[tool.commitizen.customize.bump_map_major_version_zero]",
        bump_map(cfg, major_version_zero=True),
    )
    out += ["", "# Commit type -> changelog heading. Types left out never appear in it."]
    out += _table("[tool.commitizen.customize.change_type_map]", change_type_map(cfg))
    for question in questions(cfg):
        out += [""] + _question_lines(question)
    return out


def settings_toml(cfg: CommitizenConfig) -> str:
    """The `[tool.commitizen]` block on its own — identical whether it lands in
    `.cz.toml` or inside a `pyproject.toml`, which is what makes the splice safe."""
    lines = _settings_lines(cfg)
    if cfg.customizable:
        lines += [""] + _customize_lines(cfg)
    return "\n".join(lines) + "\n"


def to_toml(cfg: CommitizenConfig) -> str:
    """A complete standalone config file (`.cz.toml`)."""
    types = ", ".join(t.key for t in cfg.selected()) if cfg.customizable else "conventional"
    header = [
        GENERATED_HEADER,
        "# Generated by `devstuff configure commitizen` — edit freely, or re-run the wizard.",
        f"# Convention: {cfg.convention_spec.label} · Types: {types}",
        f"# Option reference: {DOCS_URL}",
        "",
    ]
    return "\n".join(header) + settings_toml(cfg)


# ---------------------------------------------------------------------------
# Splicing into an existing pyproject.toml
# ---------------------------------------------------------------------------


def _trim_trailing(lines: list[str]) -> None:
    while lines and not lines[-1].strip():
        lines.pop()


def _is_header(line: str) -> bool:
    return line.lstrip().startswith("[")


def _is_commitizen_header(line: str) -> bool:
    stripped = line.lstrip()
    for prefix in ("[tool.commitizen", "[[tool.commitizen"):
        if stripped.startswith(prefix):
            rest = stripped[len(prefix) :]
            if rest[:1] in ("]", "."):
                return True
    return False


def splice_pyproject(text: str, cfg: CommitizenConfig) -> str | None:
    """Replace every `[tool.commitizen…]` table in `text` with this config's block.

    Everything outside those tables is preserved byte for byte — the file belongs to
    the project, not to the wizard. Returns `None` when the result does not parse
    back to exactly the settings we meant to write, which is the fail-closed answer
    to a `pyproject.toml` whose shape this line-based splice cannot handle (a table
    header inside a multi-line string, say). The caller falls back to `.cz.toml`.
    """
    lines = text.splitlines()
    kept: list[str] = []
    insert_at: int | None = None
    dropping = False

    for line in lines:
        if _is_commitizen_header(line):
            if insert_at is None:
                # A run of comments immediately above the table belongs to it, so it
                # goes too — otherwise the previous run's header comment survives to
                # describe the new block. Blank lines around it go with it.
                _trim_trailing(kept)
                while kept and kept[-1].lstrip().startswith("#"):
                    kept.pop()
                _trim_trailing(kept)
                # Recorded *after* the trimming, or it points past what is left.
                insert_at = len(kept)
            dropping = True
            continue
        if dropping and _is_header(line):
            dropping = False
        if not dropping:
            kept.append(line)

    block = [PYPROJECT_MARKER] + settings_toml(cfg).rstrip("\n").split("\n")
    if insert_at is None:
        _trim_trailing(kept)
        merged = kept + [""] + block
    else:
        tail = kept[insert_at:]
        while tail and not tail[0].strip():
            tail.pop(0)
        merged = kept[:insert_at] + block + ([""] + tail if tail else [])

    out = "\n".join(merged).rstrip("\n") + "\n"
    return out if _matches(out, cfg) else None


def _matches(text: str, cfg: CommitizenConfig) -> bool:
    """Whether `text` parses and its commitizen settings are exactly ours.

    Comparing parsed data rather than checking the text is what makes the splice
    safe to trust: a stray leftover key or a header swallowed by a string literal
    changes this comparison, and any parse error is a straight `False`.
    """
    try:
        parsed = tomllib.loads(text)
        expected = tomllib.loads(settings_toml(cfg))
    except tomllib.TOMLDecodeError:
        return False
    return parsed.get("tool", {}).get("commitizen") == expected["tool"]["commitizen"]


# ---------------------------------------------------------------------------
# Offline preview
# ---------------------------------------------------------------------------


def sample_message(cfg: CommitizenConfig, *, breaking: bool = False) -> str:
    """The commit message `cz commit` would produce, rendered by hand from the same
    template that goes into the file — no Jinja2 dependency for a two-field sample."""
    selected = cfg.selected()
    key = selected[0].key if selected else "feat"
    scope = "(search)" if cfg.ask_scope else ""
    bang = "!" if breaking else ""
    out = f"{key}{scope}{bang}: add rate limiting"
    if cfg.ask_body:
        out += "\n\nrequests over 100/min now get a 429 instead of timing out"
    if cfg.ask_footer and breaking:
        out += f"\n\n{BREAKING_KEYWORD}: clients must handle 429"
    return out


def bump_rows(cfg: CommitizenConfig) -> list[tuple[str, str, str]]:
    """(type, increment, resulting version) for every selected type, plus the two
    breaking-change forms. What the review screen prints, and what the live `cz`
    check is compared against."""
    rows: list[tuple[str, str, str]] = []
    for change_type in cfg.selected():
        level = change_type.bump
        rows.append((f"{change_type.key}: …", level or "—", SAMPLE_BUMPS[level]))
    breaking = MINOR if cfg.major_version_zero else MAJOR
    rows.append((f"{_first_key(cfg)}!: …", breaking, SAMPLE_BUMPS[breaking]))
    rows.append((f"{BREAKING_KEYWORD}: … (footer)", breaking, SAMPLE_BUMPS[breaking]))
    return rows


def changelog_rows(cfg: CommitizenConfig) -> list[tuple[str, list[str]]]:
    """(changelog heading, what is filed under it) in emitted order.

    The breaking-change heading only collects commits carrying a `BREAKING CHANGE:`
    *footer* — checked against the binary. A `feat!:` still bumps the major, but it
    is written up under Features, because that is the type it declared.
    """
    grouped: dict[str, list[str]] = {section: [] for section in change_type_order(cfg)}
    for change_type in cfg.changelog_types():
        grouped[change_type.section].append(change_type.key)
    grouped[BREAKING_SECTION] = [f"commits with a {BREAKING_KEYWORD}: footer"]
    return list(grouped.items())


def _first_key(cfg: CommitizenConfig) -> str:
    selected = cfg.selected()
    return selected[0].key if selected else "feat"


def summary(cfg: CommitizenConfig) -> list[tuple[str, str]]:
    """(label, value) pairs for the review screen."""
    types = cfg.selected()
    bumping = [t.key for t in types if t.bump != NONE]
    return [
        ("Convention", cfg.convention_spec.label),
        ("Commit types", f"{len(types)} — {', '.join(t.key for t in types)}"),
        ("Bumping types", ", ".join(bumping) if bumping else "none"),
        ("Changelog sections", ", ".join(s for s, _ in changelog_rows(cfg))),
        ("Version from", cfg.provider_spec.label),
        ("Version scheme", cfg.version_scheme),
        ("Tag format", cfg.tag_format.replace("$version", SAMPLE_VERSION)),
        ("Changelog on bump", "yes" if cfg.update_changelog_on_bump else "no"),
        ("0.x mode", "yes — breaking changes bump the minor" if cfg.major_version_zero else "no"),
        ("Writes to", cfg.target),
    ]


def unchangelogged(cfg: CommitizenConfig) -> list[ChangeType]:
    return [t for t in cfg.selected() if not t.changelog]
