"""Turn an `AnsibleConfig` into `ansible.cfg`, and describe it for the review screen.

`ansible.cfg` is INI, which Python can both write and read — so unlike the pre-commit
YAML emitter there is no quoting minefield. Two things still need care:

- **Booleans.** ansible's INI parser accepts `True`/`False`, and that is what
  `ansible-config init` writes, so that is what this writes. Not `yes`/`no`, which is
  also accepted but does not match anything else ansible produces.
- **Values are written raw, with no quoting at all.** This is the exact opposite of
  the bat emitter's rule, which is why the two are not shared, and both halves were
  measured:

      inventory = "./inv"      ->  DEFAULT_HOST_LIST = ['/tmp/acfg/"./inv"']
      pipelining = "True"      ->  ANSIBLE_PIPELINING = False

  A quoted path becomes a path *containing quote characters*. A quoted boolean is a
  non-empty string that ansible's coercion reads as **False** — so quoting a boolean
  silently inverts it, with no error anywhere.

The comments are the deliverable — an `ansible.cfg` is a file people go on editing —
so the emitter writes text and `matches()` parses it back with `configparser` and
compares against `data()`.
"""

from __future__ import annotations

import configparser
import io

from dev_setup.configure.ansible.model import SETTINGS, AnsibleConfig, Setting

GENERATED_HEADER = "# Generated by devstuff — devstuff configure ansible"


def _value(setting: Setting, value: object) -> str:
    """The INI text for a value.

    Written raw. ansible does not strip quotes, so a quoted path stays quoted and
    then does not exist.
    """
    if setting.kind == "bool":
        # What `ansible-config init` itself writes.
        return "True" if value else "False"
    return str(value)


def data(cfg: AnsibleConfig) -> dict[str, dict[str, str]]:
    """The config as {section: {key: value}}, in emission order."""
    out: dict[str, dict[str, str]] = {}
    for section, settings in cfg.by_section().items():
        body = {
            setting.ini_key: _value(setting, getattr(cfg, setting.key))
            for setting in settings
        }
        carried = cfg.extra.get(section, {})
        for key, value in carried.items():
            body.setdefault(key, value)
        if body:
            out[section] = body
    return out


def to_text(cfg: AnsibleConfig) -> str:
    """The file as it will be written, with comments."""
    lines = [
        GENERATED_HEADER,
        "#",
        "# Ansible reads the FIRST of these that exists:",
        "#   $ANSIBLE_CONFIG, ./ansible.cfg, ~/.ansible.cfg, /etc/ansible/ansible.cfg",
        "# — and it ignores ./ansible.cfg entirely if the directory is world-writable.",
        "#",
        "# Every setting here is one ansible-core actually reads; check with:",
        "#   ansible-config dump --only-changed",
        "",
    ]

    rendered = data(cfg)
    by_key = {setting.ini_key: setting for setting in SETTINGS.values()}

    for section, body in rendered.items():
        lines.append(f"[{section}]")
        for key, value in body.items():
            setting = by_key.get(key)
            if setting is not None and setting.why:
                for chunk in _wrap(setting.why):
                    lines.append(f"# {chunk}")
            elif setting is None:
                lines.append("# kept from the previous config")
            lines.append(f"{key} = {value}")
            lines.append("")
        if lines and lines[-1] == "":
            lines.pop()
        lines.append("")

    if not rendered:
        # Comments and no section header at all. Measured: a comments-only file is
        # accepted by `ansible-config validate` *and* is still reported as
        # CONFIG_FILE, so it does the job. Writing a bare `[defaults]` instead would
        # parse back as `{"defaults": {}}` and break the round-trip check against
        # `data()` — the same shape of bug as pre-commit's empty `repos:`.
        lines.append("# Nothing is set — every ansible default applies.")

    return "\n".join(lines).rstrip("\n") + "\n"


def _wrap(text: str, width: int = 76) -> list[str]:
    import textwrap

    return textwrap.wrap(text, width=width) or [text]


def parse(text: str) -> tuple[dict[str, dict[str, str]], bool]:
    """Read an ansible.cfg into {section: {key: value}}. (parsed, ok).

    `configparser` with `strict=False`, because a real ansible.cfg can carry a
    duplicate key and ansible itself takes the last one rather than refusing to load.
    """
    parser = configparser.ConfigParser(strict=False, interpolation=None)
    try:
        parser.read_string(text)
    except configparser.Error:
        return {}, False
    return (
        {section: dict(parser.items(section)) for section in parser.sections()},
        True,
    )


def matches(text: str, cfg: AnsibleConfig) -> bool:
    """Whether the emitted text parses back to what the model meant."""
    parsed, ok = parse(text)
    if not ok:
        return False
    return parsed == data(cfg)


def to_ini_string(mapping: dict[str, dict[str, str]]) -> str:
    """Serialise a parsed structure back to INI — used by tests and diffs."""
    parser = configparser.ConfigParser(interpolation=None)
    for section, body in mapping.items():
        parser[section] = dict(body)
    buffer = io.StringIO()
    parser.write(buffer)
    return buffer.getvalue()


# ---------------------------------------------------------------------------
# Review screen
# ---------------------------------------------------------------------------


def summary(cfg: AnsibleConfig) -> list[tuple[str, str]]:
    rendered = data(cfg)
    rows = [
        ("starting point", cfg.preset),
        ("sections", ", ".join(rendered) or "none"),
        ("settings", str(sum(len(body) for body in rendered.values()))),
        ("writes to", str(cfg.target)),
    ]
    if cfg.extra:
        rows.append(("carried over", ", ".join(sorted(cfg.extra))))
    return rows


def setting_rows(cfg: AnsibleConfig) -> list[tuple[str, str, str, str]]:
    """(section, key, value, why it matters)."""
    rows: list[tuple[str, str, str, str]] = []
    for setting in cfg.changed().values():
        rows.append((
            setting.section,
            setting.ini_key,
            _value(setting, getattr(cfg, setting.key)),
            setting.why or setting.description,
        ))
    for section, body in cfg.extra.items():
        for key, value in body.items():
            rows.append((section, key, value, "carried over — not set by this wizard"))
    return rows


def diff(old: str, new: str) -> list[str]:
    import difflib

    return list(
        difflib.unified_diff(
            old.splitlines(), new.splitlines(), fromfile="current", tofile="new", lineterm=""
        )
    )


__all__ = [
    "GENERATED_HEADER",
    "data",
    "diff",
    "matches",
    "parse",
    "setting_rows",
    "summary",
    "to_ini_string",
    "to_text",
]
