"""Write the profile file, the secret files, and the shell bridge.

Three outputs, with three different audiences:

- `to_yaml()` -> `~/.config/devstuff/proxmox.yaml`, for the user to read and hand-edit.
  Hand-emitted rather than `yaml.safe_dump`ed so it can carry the comments that say what
  each field means and, more importantly, that no secret belongs in it.
- `write_secret()` -> a `0600` file under `~/.config/devstuff/secrets/`, holding one
  secret and nothing else.
- `export_shell()` -> the assignments `lib.sh` is bootstrapped with. It carries where the
  secret lives, never the secret (SD-3).
"""

from __future__ import annotations

import difflib
import json
import os
import shlex
import stat
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from dev_setup.catalog import CatalogError
from dev_setup.configure.proxmox.model import (
    CONFIG_PATH,
    CONFIG_VERSION,
    SECRETS_DIR,
    Profile,
    ProxmoxConfig,
    validate_config,
)

PACKAGE_DIR = Path(__file__).resolve().parent
LIB_PATH = PACKAGE_DIR / "lib.sh"
FMT_PATH = PACKAGE_DIR / "fmt.py"

MARKER = "# Generated by `devstuff configure proxmox`"

HEADER = f"""# Proxmox connection profiles for devstuff's pve-* functions.
{MARKER} — edit freely, or re-run the wizard.
#
# NOTHING SECRET IS STORED HERE. A profile says where its secret lives:
#   secret_env:  NAME   an environment variable in your shell
#   secret_file: PATH   a file the wizard writes, readable only by you
#
# transport: ssh   full access — the state-changing pve-* functions need this
# transport: api   read-only, over an API token, no shell access to the node
#
# See what this feeds:  devstuff functions list
"""

FIELD_NOTES = {
    "node": "the name this node has inside the cluster, if it differs from the host",
    "sudo": "run remote commands through sudo -n (qm/pct/vzdump need root)",
    "verify_tls": "a default Proxmox install serves a self-signed certificate",
    "secret_env": "name of an environment variable — not the secret itself",
    "secret_file": "path to a 0600 file — not the secret itself",
}


def _scalar(value: Any) -> str:
    """Emit a YAML scalar, asking the parser rather than guessing at the quoting rules.

    A bare string is only safe if reading it back yields the same string — which is what
    keeps a host called `on` from becoming the boolean True, and a token name like `1.0`
    from becoming a float.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value)
    if text == "":
        return '""'
    try:
        if yaml.safe_load(text) == text:
            return text
    except yaml.YAMLError:
        pass
    return json.dumps(text)


def to_yaml(cfg: ProxmoxConfig) -> str:
    lines = [HEADER, f"version: {CONFIG_VERSION}"]
    lines.append(f"default: {_scalar(cfg.default)}" if cfg.default else 'default: ""')
    lines.append("")
    if not cfg.profiles:
        # `profiles:` with nothing under it parses as null, which the loader would then
        # have to special-case. An explicit empty mapping says the same thing and loads.
        lines.append("profiles: {}")
        return "\n".join(lines) + "\n"

    lines.append("profiles:")
    for name, profile in cfg.profiles.items():
        lines.append(f"  {_scalar(name)}:")
        if profile.description:
            lines.append(f"    # {profile.description}")
        for key, value in profile.to_dict().items():
            note = FIELD_NOTES.get(key)
            if note:
                lines.append(f"    # {note}")
            lines.append(f"    {key}: {_scalar(value)}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def load(text: str, *, source: Path | str = CONFIG_PATH) -> ProxmoxConfig:
    try:
        raw = yaml.safe_load(text) or {}
    except yaml.YAMLError as exc:
        raise CatalogError(f"Invalid YAML in {source}: {exc}") from exc
    return validate_config(raw, source=source)


def matches(text: str, cfg: ProxmoxConfig) -> bool:
    """Whether emitted text reads back as the config it came from.

    The emitter writes YAML by hand for the comments, so this is what stops the two
    representations drifting apart; the round-trip test is built on it.
    """
    try:
        return load(text).to_dict() == cfg.to_dict()
    except CatalogError:
        return False


def diff(old: str, new: str) -> list[str]:
    return list(
        difflib.unified_diff(
            old.splitlines(), new.splitlines(), fromfile="current", tofile="new", lineterm=""
        )
    )


def was_generated(text: str) -> bool:
    return MARKER in text


# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------


def secret_path(profile_name: str) -> Path:
    return SECRETS_DIR / f"proxmox-{profile_name}"


def write_secret(profile_name: str, value: str) -> Path:
    """Write one secret to its own 0600 file, creating the directory 0700.

    Created with restrictive permissions from the start rather than chmod'ed afterwards:
    the window between the two is short, but it is a window in which the token is
    world-readable.
    """
    SECRETS_DIR.mkdir(parents=True, exist_ok=True)
    os.chmod(SECRETS_DIR, stat.S_IRWXU)
    path = secret_path(profile_name)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(value)
    os.chmod(path, 0o600)
    return path


# ---------------------------------------------------------------------------
# Saving
# ---------------------------------------------------------------------------


def backup(path: Path) -> Path | None:
    if not path.exists():
        return None
    dest = path.with_name(f"{path.name}.bak.{datetime.now():%Y%m%d-%H%M%S}")
    dest.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    os.chmod(dest, 0o600)
    return dest


def save(cfg: ProxmoxConfig, path: Path) -> tuple[Path, Path | None]:
    path.parent.mkdir(parents=True, exist_ok=True)
    saved = backup(path)
    text = to_yaml(cfg)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(text)
    # An existing file keeps its mode through O_CREAT, so this is not redundant: a config
    # that was once 0644 becomes 0600 on the next save.
    os.chmod(path, 0o600)
    return path, saved


# ---------------------------------------------------------------------------
# The shell bridge
# ---------------------------------------------------------------------------


def _expand(value: str) -> str:
    return str(Path(value).expanduser()) if value else ""


def export_shell(profile: Profile) -> str:
    """The assignments a pve-* function evaluates before sourcing lib.sh.

    Every value is `shlex.quote`d, so a host or path containing a space or a quote
    survives the `eval` intact. `PVE_SECRET_ENV`/`PVE_SECRET_FILE` are references: the
    secret itself is read by lib.sh at the moment it builds a request, so it never
    appears in this text, in a `set -x` trace, or in `devstuff -vv` output.
    """
    values: dict[str, str] = {
        "PVE_LIB": str(LIB_PATH),
        "PVE_FMT": str(FMT_PATH),
        "PVE_PYTHON": sys.executable or "python3",
        "PVE_PROFILE": profile.name,
        "PVE_TRANSPORT": profile.transport,
        "PVE_HOST": profile.host,
        "PVE_NODE": profile.node,
        "PVE_USER": profile.user,
        "PVE_PORT": str(profile.port),
        "PVE_AUTH": profile.auth,
        "PVE_IDENTITY": _expand(profile.identity_file),
        "PVE_SUDO": "1" if profile.sudo else "0",
        "PVE_API_PORT": str(profile.api_port),
        "PVE_TOKEN_ID": profile.token_id,
        "PVE_VERIFY_TLS": "1" if profile.verify_tls else "0",
        "PVE_SECRET_ENV": profile.secret_env,
        "PVE_SECRET_FILE": _expand(profile.secret_file),
        "PVE_ENDPOINT": profile.endpoint() if profile.transport == "api" else "",
    }
    return "\n".join(f"{key}={shlex.quote(value)}" for key, value in values.items())
